<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\libs\RE-Engine-Lib\REE-Lib\REE-Lib.csproj" />
    <ProjectReference Include="..\..\GDeflateNet\GDeflateNet\GDeflateNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
