import json,pathlib,collections
root=pathlib.Path('artifacts/preview-fix/full-audit')
s=json.load(open(root/'summary.json',encoding='utf-8'))
c=json.load(open(root/'RE4/wp4000h-all-76-review.json',encoding='utf-8'))
lines=['# 动画用途与叠加预览批量审查','', '日期：2026-09-29。源码基线：v1.4.4 / 15289c8f5239aa2d5068c0708280013365896dc2。仅本地修改。','', '## 检查范围与强度','', '本次遍历本机 Steam 安装目录中具有可用游戏文件和路径列表的 RE4、SF6、MH Wilds、鬼武者。覆盖已解析出路径的24,237个motlist；不包括路径列表未覆盖的PAK哈希。未在此次资源集中的其他游戏版本没有运行验证。解析成功不等于逐动作视觉通过，更不等于游戏完整状态机已还原。','']
for g in s['Games']:
 lines += [f"- {g['Game']}：{g['VisitedLists']}/{g['ResolvedLists']} 个列表，状态 {g['States']}；枚举到 {g['EmbeddedMotions']} 个内嵌MOT，{g['ListsWithBaseReference']} 个列表引用基础列表。"]
lines += ['', 'SF6的HEADER_ONLY仅检查列表、动作编号和MOT头信息，没有完整解码曲线。完整解析在 npc8091_01_om15000_009_2m.motlist.653 出现异常内存增长，已停止该检查进程；该文件没有被认定为可正常预览。80个解析错误和上述限制保留在summary.json，未更改游戏资源或第三方解析器来掩盖失败。', '', 'RE4另外遍历891个motfsm2：846个解析成功、45个失败。失败条目和错误信息保存在summary.json。部分解析器还报告RSZ CRC不匹配，相关解析结果不能替代游戏运行验证。', '', '## 已修正的共同问题','', '- 不再把“没有识别成ADD”等同于完整主动作。列表改称动作轨道，显示配置附加、配置覆盖、状态相关、名称疑似、用途未核实。所有游戏的加载入口都显示用途边界。', '- 使用玩家Prefab的有序层、启用的FSM动作、motbank映射和实际motlist轨道生成用途证据，键包含完整资源路径、编号和轨道名。当前记录1437条，覆盖69个列表：258条附加、1099条覆盖、80条状态相关。这些是该玩家配置中的可能用途，不是所有运行状态的完整模拟。', '- 其中25条附加轨道没有_add后缀，涉及多种武器的危险持枪、空弹、射击后续及general2的擦弹反应；此前仅修161/520并不足够。原有单独核实的500/501/502继续保留，未扩散到其他资源。', '- 名称含_add但缺少配置证据的条目标为“疑似附加（名称）”；其他未确认轨道明确标注用途未核实。没有按编号相邻、名称近似或位移幅度建立新的配对。', '- 配对查询本身删除同名推测，仅返回原有7组已确认且已支持层序/遮罩的配对。用途证据新增不代表新增组合预览支持。', '- 纠正右键加载动画后的“已叠加”提示：实际是加载单条轨道。两个首次加载入口与后续切换使用同一预览处理，避免首条ADD被过滤后界面选择和实际播放不一致。', '- 仅含附加/疑似附加轨道的列表自动进入明确的原始检查模式；折叠说明不会丢失轨道或伪装成主动作。原始导出索引保持不变。', '', '## 当前wp4000H列表逐条记录','', f"76条全部列于 RE4/wp4000h-all-76-review.json。分类数量：{dict(collections.Counter(x['Usage'] for x in c))}。Unknown和AdditiveHint均不表示已核实用途。", '', '## 验证与剩余边界','', 'ui-r6.log覆盖筛选、跨资源同编号隔离、名称与配置证据区别、覆盖层/多状态/未知用途提示、仅附加列表、所有48个普通可选轨道的原始导出映射和失败恢复。layers-r6.log核对真实层序并保留11组动作的全帧0/50/100%检查。native-r6.log记录完整模型的原生预览检查；这些是有限代表场景，不是227370条动作的逐帧视觉验收。', '', '当前仍未完整还原状态机条件、动态Bank选择、层权重、所有遮罩切换、底层移动和IK。SF6解析失败、未解析路径哈希、外部引用动作、其他游戏的层用途证据仍是明确缺口。不得将这次批量扫描称为全部游戏动画已经正常。', '', '当前测试程序：../app-r6/ReExtractor-v1.4.4.exe；构建、校验及加载状态分别见publish-r6.log、build-verification-r6.json、showcase-r6.json.result.json。']
(root/'批量审查记录.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(dict(collections.Counter(x['Usage'] for x in c)))
print('REPORT_WRITTEN')
