using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Interactivity;
using Avalonia.Themes.Fluent;
using Avalonia.Styling;
using Avalonia.Threading;
using Avalonia.VisualTree;
using ReExtractor.Core;
using ReExtractor.Gui;

AppBuilder.Configure<Application>().UseSkia().UseHeadless(new AvaloniaHeadlessPlatformOptions { UseHeadlessDrawing = false }).SetupWithoutStarting();
Application.Current!.Styles.Add(new FluentTheme());
Application.Current.RequestedThemeVariant = ThemeVariant.Dark;
var owner = new Window(); owner.Show();
const string stem = "natives/stm/art/model/character/ch2/ch210/50/40/ch210_50_40";
var resolution = new MaterialResolution(stem + ".mesh.260209350", null,
    Enumerable.Range(1, 3).Select(i => new MaterialCandidate(stem + $"_o{i}.mdf2.51", 1, 1)).ToArray(), []);
var window = new MaterialSelectionWindow(resolution);
var result = window.ShowDialog<string?>(owner);
Dispatcher.UIThread.RunJobs();
var list = window.GetVisualDescendants().OfType<ListBox>().Single();
var apply = window.GetVisualDescendants().OfType<Button>().Single(b => b.Name == "ApplyMaterial");
if (list.SelectedIndex != -1 || apply.IsEnabled) throw new Exception("A default was silently chosen");
list.SelectedIndex = 1;
Dispatcher.UIThread.RunJobs();
if (!apply.IsEnabled) throw new Exception("Cannot confirm selection");
var output = Path.GetFullPath("artifacts/material_resolver/selection.png");
Directory.CreateDirectory(Path.GetDirectoryName(output)!);
using (var bitmap = window.CaptureRenderedFrame()) bitmap?.Save(output);
apply.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
Dispatcher.UIThread.RunJobs();
if (!result.IsCompleted || result.Result != stem + "_o2.mdf2.51") throw new Exception("Wrong choice returned");
var cancelWindow = new MaterialSelectionWindow(resolution);
var cancelled = cancelWindow.ShowDialog<string?>(owner);
Dispatcher.UIThread.RunJobs();
cancelWindow.GetVisualDescendants().OfType<Button>().Single(b => b.Name == "CancelMaterial").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
Dispatcher.UIThread.RunJobs();
if (!cancelled.IsCompleted || cancelled.Result != null) throw new Exception("Cancel selected a material");
owner.Close();
Console.WriteLine("MATERIAL_SELECTION_UI_PASS no default, explicit o2 selection, cancellation");
